language: python
python:
  - "2.7"
before_install:
  - sudo pip install dulwich
  - curl -L https://bootstrap.saltstack.com | sudo sh
install:
  - sudo salt-call --local --config-dir=./ state.highstate
script: echo "script"
